---
micronaut:
  application:
    name: elasticsearch-ecommerce-search-app
  server:
    port: 4000
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths:
#          - classpath:static
          - file:src/main/resources/static

---
elasticsearch:
  httpHosts: "http://localhost:8080"

---
# WARNING: MASSIVW SECURITY HOLE!
endpoints:
  all:
    sensitive: false
    enabled: true

---
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
